services:
  dashboard:
    image: crypto-dashboard
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - /datas/dashboard/icons:/home/node/app/public/images/icons
    restart: unless-stopped
  updater:
    image: crypto-updater
    build: ../crypto-updater
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:4.4
    volumes:
      - /datas/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
